export type Country = {
    name: string;
    iso2: string;
    dialCode: string;
    flag: string;
    format?: string;
    maxLength?: number;
};


function getFlag(iso2: string): string {
    const codePoints = iso2
        .toUpperCase()
        .split('')
        .map(char => 0x1F1E6 + char.charCodeAt(0) - 65);
    return String.fromCodePoint(...codePoints);
}


export const DEFAULT_COUNTRY = 'IN';


export const COUNTRY_CODE: Country[] = [
    { name: 'India',          iso2: 'IN', dialCode: '+91',  flag: getFlag('IN'), format: 'XXXXX XXXXX', maxLength: 10 },
    { name: 'United States',  iso2: 'US', dialCode: '+1',   flag: getFlag('US'), format: '(XXX) XXX-XXXX', maxLength: 10 },
    { name: 'United Kingdom', iso2: 'GB', dialCode: '+44',  flag: getFlag('GB'), format: 'XXXX XXXXXX', maxLength: 10 },
    { name: 'Canada',         iso2: 'CA', dialCode: '+1',   flag: getFlag('CA'), format: '(XXX) XXX-XXXX', maxLength: 10 },
    { name: 'Australia',      iso2: 'AU', dialCode: '+61',  flag: getFlag('AU'), format: 'XXXX XXX XXX', maxLength: 9 },

    { name: 'Afghanistan',              iso2: 'AF', dialCode: '+93',   flag: getFlag('AF'), maxLength: 9 },
    { name: 'Albania',                  iso2: 'AL', dialCode: '+355',  flag: getFlag('AL'), maxLength: 9 },
    { name: 'Algeria',                  iso2: 'DZ', dialCode: '+213',  flag: getFlag('DZ'), maxLength: 9 },
    { name: 'Andorra',                  iso2: 'AD', dialCode: '+376',  flag: getFlag('AD'), maxLength: 9 },
    { name: 'Angola',                   iso2: 'AO', dialCode: '+244',  flag: getFlag('AO'), maxLength: 9 },
    { name: 'Argentina',                iso2: 'AR', dialCode: '+54',   flag: getFlag('AR'), maxLength: 10 },
    { name: 'Armenia',                  iso2: 'AM', dialCode: '+374',  flag: getFlag('AM'), maxLength: 8 },
    { name: 'Austria',                  iso2: 'AT', dialCode: '+43',   flag: getFlag('AT'), maxLength: 11 },
    { name: 'Azerbaijan',               iso2: 'AZ', dialCode: '+994',  flag: getFlag('AZ'), maxLength: 9 },
    { name: 'Bahamas',                  iso2: 'BS', dialCode: '+1242', flag: getFlag('BS'), maxLength: 7 },
    { name: 'Bahrain',                  iso2: 'BH', dialCode: '+973',  flag: getFlag('BH'), maxLength: 8 },
    { name: 'Bangladesh',               iso2: 'BD', dialCode: '+880',  flag: getFlag('BD'), maxLength: 10 },
    { name: 'Barbados',                 iso2: 'BB', dialCode: '+1246', flag: getFlag('BB'), maxLength: 7 },
    { name: 'Belarus',                  iso2: 'BY', dialCode: '+375',  flag: getFlag('BY'), maxLength: 10 },
    { name: 'Belgium',                  iso2: 'BE', dialCode: '+32',   flag: getFlag('BE'), maxLength: 9 },
    { name: 'Belize',                   iso2: 'BZ', dialCode: '+501',  flag: getFlag('BZ'), maxLength: 7 },
    { name: 'Benin',                    iso2: 'BJ', dialCode: '+229',  flag: getFlag('BJ'), maxLength: 8 },
    { name: 'Bhutan',                   iso2: 'BT', dialCode: '+975',  flag: getFlag('BT'), maxLength: 8 },
    { name: 'Bolivia',                  iso2: 'BO', dialCode: '+591',  flag: getFlag('BO'), maxLength: 8 },
    { name: 'Bosnia and Herzegovina',   iso2: 'BA', dialCode: '+387',  flag: getFlag('BA'), maxLength: 8 },
    { name: 'Botswana',                 iso2: 'BW', dialCode: '+267',  flag: getFlag('BW'), maxLength: 8 },
    { name: 'Brazil',                   iso2: 'BR', dialCode: '+55',   flag: getFlag('BR'), maxLength: 11 },
    { name: 'Brunei',                   iso2: 'BN', dialCode: '+673',  flag: getFlag('BN'), maxLength: 7 },
    { name: 'Bulgaria',                 iso2: 'BG', dialCode: '+359',  flag: getFlag('BG'), maxLength: 9 },
    { name: 'Burkina Faso',             iso2: 'BF', dialCode: '+226',  flag: getFlag('BF'), maxLength: 8 },
    { name: 'Burundi',                  iso2: 'BI', dialCode: '+257',  flag: getFlag('BI'), maxLength: 8 },
    { name: 'Cambodia',                 iso2: 'KH', dialCode: '+855',  flag: getFlag('KH'), maxLength: 9 },
    { name: 'Cameroon',                 iso2: 'CM', dialCode: '+237',  flag: getFlag('CM'), maxLength: 9 },
    { name: 'Cape Verde',               iso2: 'CV', dialCode: '+238',  flag: getFlag('CV'), maxLength: 7 },
    { name: 'Central African Republic', iso2: 'CF', dialCode: '+236',  flag: getFlag('CF'), maxLength: 8 },
    { name: 'Chad',                     iso2: 'TD', dialCode: '+235',  flag: getFlag('TD'), maxLength: 8 },
    { name: 'Chile',                    iso2: 'CL', dialCode: '+56',   flag: getFlag('CL'), maxLength: 9 },
    { name: 'China',                    iso2: 'CN', dialCode: '+86',   flag: getFlag('CN'), maxLength: 11 },
    { name: 'Colombia',                 iso2: 'CO', dialCode: '+57',   flag: getFlag('CO'), maxLength: 10 },
    { name: 'Comoros',                  iso2: 'KM', dialCode: '+269',  flag: getFlag('KM'), maxLength: 7 },
    { name: 'Congo',                    iso2: 'CG', dialCode: '+242',  flag: getFlag('CG'), maxLength: 9 },
    { name: 'Congo (DRC)',              iso2: 'CD', dialCode: '+243',  flag: getFlag('CD'), maxLength: 9 },
    { name: 'Costa Rica',               iso2: 'CR', dialCode: '+506',  flag: getFlag('CR'), maxLength: 8 },
    { name: 'Croatia',                  iso2: 'HR', dialCode: '+385',  flag: getFlag('HR'), maxLength: 9 },
    { name: 'Cuba',                     iso2: 'CU', dialCode: '+53',   flag: getFlag('CU'), maxLength: 8 },
    { name: 'Cyprus',                   iso2: 'CY', dialCode: '+357',  flag: getFlag('CY'), maxLength: 8 },
    { name: 'Czech Republic',           iso2: 'CZ', dialCode: '+420',  flag: getFlag('CZ'), maxLength: 9 },
    { name: 'Denmark',                  iso2: 'DK', dialCode: '+45',   flag: getFlag('DK'), maxLength: 8 },
    { name: 'Djibouti',                 iso2: 'DJ', dialCode: '+253',  flag: getFlag('DJ'), maxLength: 8 },
    { name: 'Dominican Republic',       iso2: 'DO', dialCode: '+1809', flag: getFlag('DO'), maxLength: 7 },
    { name: 'Ecuador',                  iso2: 'EC', dialCode: '+593',  flag: getFlag('EC'), maxLength: 9 },
    { name: 'Egypt',                    iso2: 'EG', dialCode: '+20',   flag: getFlag('EG'), maxLength: 10 },
    { name: 'El Salvador',              iso2: 'SV', dialCode: '+503',  flag: getFlag('SV'), maxLength: 8 },
    { name: 'Equatorial Guinea',        iso2: 'GQ', dialCode: '+240',  flag: getFlag('GQ'), maxLength: 9 },
    { name: 'Eritrea',                  iso2: 'ER', dialCode: '+291',  flag: getFlag('ER'), maxLength: 7 },
    { name: 'Estonia',                  iso2: 'EE', dialCode: '+372',  flag: getFlag('EE'), maxLength: 8 },
    { name: 'Eswatini',                 iso2: 'SZ', dialCode: '+268',  flag: getFlag('SZ'), maxLength: 8 },
    { name: 'Ethiopia',                 iso2: 'ET', dialCode: '+251',  flag: getFlag('ET'), maxLength: 9 },
    { name: 'Fiji',                     iso2: 'FJ', dialCode: '+679',  flag: getFlag('FJ'), maxLength: 7 },
    { name: 'Finland',                  iso2: 'FI', dialCode: '+358',  flag: getFlag('FI'), maxLength: 10 },
    { name: 'France',                   iso2: 'FR', dialCode: '+33',   flag: getFlag('FR'), format: 'X XX XX XX XX', maxLength: 9 },
    { name: 'Gabon',                    iso2: 'GA', dialCode: '+241',  flag: getFlag('GA'), maxLength: 8 },
    { name: 'Gambia',                   iso2: 'GM', dialCode: '+220',  flag: getFlag('GM'), maxLength: 7 },
    { name: 'Georgia',                  iso2: 'GE', dialCode: '+995',  flag: getFlag('GE'), maxLength: 9 },
    { name: 'Germany',                  iso2: 'DE', dialCode: '+49',   flag: getFlag('DE'), format: 'XXXX XXXXXXX', maxLength: 11 },
    { name: 'Ghana',                    iso2: 'GH', dialCode: '+233',  flag: getFlag('GH'), maxLength: 9 },
    { name: 'Greece',                   iso2: 'GR', dialCode: '+30',   flag: getFlag('GR'), maxLength: 10 },
    { name: 'Guatemala',                iso2: 'GT', dialCode: '+502',  flag: getFlag('GT'), maxLength: 8 },
    { name: 'Guinea',                   iso2: 'GN', dialCode: '+224',  flag: getFlag('GN'), maxLength: 9 },
    { name: 'Guyana',                   iso2: 'GY', dialCode: '+592',  flag: getFlag('GY'), maxLength: 7 },
    { name: 'Haiti',                    iso2: 'HT', dialCode: '+509',  flag: getFlag('HT'), maxLength: 8 },
    { name: 'Honduras',                 iso2: 'HN', dialCode: '+504',  flag: getFlag('HN'), maxLength: 8 },
    { name: 'Hong Kong',                iso2: 'HK', dialCode: '+852',  flag: getFlag('HK'), maxLength: 8 },
    { name: 'Hungary',                  iso2: 'HU', dialCode: '+36',   flag: getFlag('HU'), maxLength: 9 },
    { name: 'Iceland',                  iso2: 'IS', dialCode: '+354',  flag: getFlag('IS'), maxLength: 7 },
    { name: 'Indonesia',                iso2: 'ID', dialCode: '+62',   flag: getFlag('ID'), maxLength: 11 },
    { name: 'Iran',                     iso2: 'IR', dialCode: '+98',   flag: getFlag('IR'), maxLength: 10 },
    { name: 'Iraq',                     iso2: 'IQ', dialCode: '+964',  flag: getFlag('IQ'), maxLength: 10 },
    { name: 'Ireland',                  iso2: 'IE', dialCode: '+353',  flag: getFlag('IE'), maxLength: 9 },
    { name: 'Israel',                   iso2: 'IL', dialCode: '+972',  flag: getFlag('IL'), maxLength: 9 },
    { name: 'Italy',                    iso2: 'IT', dialCode: '+39',   flag: getFlag('IT'), maxLength: 10 },
    { name: 'Ivory Coast',              iso2: 'CI', dialCode: '+225',  flag: getFlag('CI'), maxLength: 10 },
    { name: 'Jamaica',                  iso2: 'JM', dialCode: '+1876', flag: getFlag('JM'), maxLength: 7 },
    { name: 'Japan',                    iso2: 'JP', dialCode: '+81',   flag: getFlag('JP'), format: 'XXX-XXXX-XXXX', maxLength: 10 },
    { name: 'Jordan',                   iso2: 'JO', dialCode: '+962',  flag: getFlag('JO'), maxLength: 9 },
    { name: 'Kazakhstan',               iso2: 'KZ', dialCode: '+7',    flag: getFlag('KZ'), maxLength: 10 },
    { name: 'Kenya',                    iso2: 'KE', dialCode: '+254',  flag: getFlag('KE'), maxLength: 10 },
    { name: 'Kuwait',                   iso2: 'KW', dialCode: '+965',  flag: getFlag('KW'), maxLength: 8 },
    { name: 'Kyrgyzstan',               iso2: 'KG', dialCode: '+996',  flag: getFlag('KG'), maxLength: 9 },
    { name: 'Laos',                     iso2: 'LA', dialCode: '+856',  flag: getFlag('LA'), maxLength: 10 },
    { name: 'Latvia',                   iso2: 'LV', dialCode: '+371',  flag: getFlag('LV'), maxLength: 8 },
    { name: 'Lebanon',                  iso2: 'LB', dialCode: '+961',  flag: getFlag('LB'), maxLength: 8 },
    { name: 'Lesotho',                  iso2: 'LS', dialCode: '+266',  flag: getFlag('LS'), maxLength: 8 },
    { name: 'Liberia',                  iso2: 'LR', dialCode: '+231',  flag: getFlag('LR'), maxLength: 8 },
    { name: 'Libya',                    iso2: 'LY', dialCode: '+218',  flag: getFlag('LY'), maxLength: 10 },
    { name: 'Liechtenstein',            iso2: 'LI', dialCode: '+423',  flag: getFlag('LI'), maxLength: 7 },
    { name: 'Lithuania',                iso2: 'LT', dialCode: '+370',  flag: getFlag('LT'), maxLength: 8 },
    { name: 'Luxembourg',               iso2: 'LU', dialCode: '+352',  flag: getFlag('LU'), maxLength: 9 },
    { name: 'Macau',                    iso2: 'MO', dialCode: '+853',  flag: getFlag('MO'), maxLength: 8 },
    { name: 'Madagascar',               iso2: 'MG', dialCode: '+261',  flag: getFlag('MG'), maxLength: 10 },
    { name: 'Malawi',                   iso2: 'MW', dialCode: '+265',  flag: getFlag('MW'), maxLength: 9 },
    { name: 'Malaysia',                 iso2: 'MY', dialCode: '+60',   flag: getFlag('MY'), maxLength: 10 },
    { name: 'Maldives',                 iso2: 'MV', dialCode: '+960',  flag: getFlag('MV'), maxLength: 7 },
    { name: 'Mali',                     iso2: 'ML', dialCode: '+223',  flag: getFlag('ML'), maxLength: 8 },
    { name: 'Malta',                    iso2: 'MT', dialCode: '+356',  flag: getFlag('MT'), maxLength: 8 },
    { name: 'Mauritania',               iso2: 'MR', dialCode: '+222',  flag: getFlag('MR'), maxLength: 8 },
    { name: 'Mauritius',                iso2: 'MU', dialCode: '+230',  flag: getFlag('MU'), maxLength: 8 },
    { name: 'Mexico',                   iso2: 'MX', dialCode: '+52',   flag: getFlag('MX'), maxLength: 10 },
    { name: 'Moldova',                  iso2: 'MD', dialCode: '+373',  flag: getFlag('MD'), maxLength: 8 },
    { name: 'Monaco',                   iso2: 'MC', dialCode: '+377',  flag: getFlag('MC'), maxLength: 8 },
    { name: 'Mongolia',                 iso2: 'MN', dialCode: '+976',  flag: getFlag('MN'), maxLength: 8 },
    { name: 'Montenegro',               iso2: 'ME', dialCode: '+382',  flag: getFlag('ME'), maxLength: 8 },
    { name: 'Morocco',                  iso2: 'MA', dialCode: '+212',  flag: getFlag('MA'), maxLength: 9 },
    { name: 'Mozambique',               iso2: 'MZ', dialCode: '+258',  flag: getFlag('MZ'), maxLength: 9 },
    { name: 'Myanmar',                  iso2: 'MM', dialCode: '+95',   flag: getFlag('MM'), maxLength: 10 },
    { name: 'Namibia',                  iso2: 'NA', dialCode: '+264',  flag: getFlag('NA'), maxLength: 9 },
    { name: 'Nepal',                    iso2: 'NP', dialCode: '+977',  flag: getFlag('NP'), maxLength: 10 },
    { name: 'Netherlands',              iso2: 'NL', dialCode: '+31',   flag: getFlag('NL'), maxLength: 9 },
    { name: 'New Zealand',              iso2: 'NZ', dialCode: '+64',   flag: getFlag('NZ'), maxLength: 10 },
    { name: 'Nicaragua',                iso2: 'NI', dialCode: '+505',  flag: getFlag('NI'), maxLength: 8 },
    { name: 'Niger',                    iso2: 'NE', dialCode: '+227',  flag: getFlag('NE'), maxLength: 8 },
    { name: 'Nigeria',                  iso2: 'NG', dialCode: '+234',  flag: getFlag('NG'), maxLength: 10 },
    { name: 'North Korea',              iso2: 'KP', dialCode: '+850',  flag: getFlag('KP'), maxLength: 10 },
    { name: 'North Macedonia',          iso2: 'MK', dialCode: '+389',  flag: getFlag('MK'), maxLength: 8 },
    { name: 'Norway',                   iso2: 'NO', dialCode: '+47',   flag: getFlag('NO'), maxLength: 8 },
    { name: 'Oman',                     iso2: 'OM', dialCode: '+968',  flag: getFlag('OM'), maxLength: 8 },
    { name: 'Pakistan',                 iso2: 'PK', dialCode: '+92',   flag: getFlag('PK'), maxLength: 10 },
    { name: 'Palestine',                iso2: 'PS', dialCode: '+970',  flag: getFlag('PS'), maxLength: 9 },
    { name: 'Panama',                   iso2: 'PA', dialCode: '+507',  flag: getFlag('PA'), maxLength: 8 },
    { name: 'Papua New Guinea',         iso2: 'PG', dialCode: '+675',  flag: getFlag('PG'), maxLength: 8 },
    { name: 'Paraguay',                 iso2: 'PY', dialCode: '+595',  flag: getFlag('PY'), maxLength: 9 },
    { name: 'Peru',                     iso2: 'PE', dialCode: '+51',   flag: getFlag('PE'), maxLength: 9 },
    { name: 'Philippines',              iso2: 'PH', dialCode: '+63',   flag: getFlag('PH'), maxLength: 10 },
    { name: 'Poland',                   iso2: 'PL', dialCode: '+48',   flag: getFlag('PL'), maxLength: 9 },
    { name: 'Portugal',                 iso2: 'PT', dialCode: '+351',  flag: getFlag('PT'), maxLength: 9 },
    { name: 'Qatar',                    iso2: 'QA', dialCode: '+974',  flag: getFlag('QA'), maxLength: 8 },
    { name: 'Romania',                  iso2: 'RO', dialCode: '+40',   flag: getFlag('RO'), maxLength: 10 },
    { name: 'Russia',                   iso2: 'RU', dialCode: '+7',    flag: getFlag('RU'), maxLength: 10 },
    { name: 'Rwanda',                   iso2: 'RW', dialCode: '+250',  flag: getFlag('RW'), maxLength: 9 },
    { name: 'Saudi Arabia',             iso2: 'SA', dialCode: '+966',  flag: getFlag('SA'), maxLength: 9 },
    { name: 'Senegal',                  iso2: 'SN', dialCode: '+221',  flag: getFlag('SN'), maxLength: 9 },
    { name: 'Serbia',                   iso2: 'RS', dialCode: '+381',  flag: getFlag('RS'), maxLength: 9 },
    { name: 'Sierra Leone',             iso2: 'SL', dialCode: '+232',  flag: getFlag('SL'), maxLength: 8 },
    { name: 'Singapore',                iso2: 'SG', dialCode: '+65',   flag: getFlag('SG'), maxLength: 8 },
    { name: 'Slovakia',                 iso2: 'SK', dialCode: '+421',  flag: getFlag('SK'), maxLength: 9 },
    { name: 'Slovenia',                 iso2: 'SI', dialCode: '+386',  flag: getFlag('SI'), maxLength: 8 },
    { name: 'Somalia',                  iso2: 'SO', dialCode: '+252',  flag: getFlag('SO'), maxLength: 8 },
    { name: 'South Africa',             iso2: 'ZA', dialCode: '+27',   flag: getFlag('ZA'), maxLength: 9 },
    { name: 'South Korea',              iso2: 'KR', dialCode: '+82',   flag: getFlag('KR'), format: 'XXX-XXXX-XXXX', maxLength: 11 },
    { name: 'South Sudan',              iso2: 'SS', dialCode: '+211',  flag: getFlag('SS'), maxLength: 9 },
    { name: 'Spain',                    iso2: 'ES', dialCode: '+34',   flag: getFlag('ES'), maxLength: 9 },
    { name: 'Sri Lanka',                iso2: 'LK', dialCode: '+94',   flag: getFlag('LK'), maxLength: 9 },
    { name: 'Sudan',                    iso2: 'SD', dialCode: '+249',  flag: getFlag('SD'), maxLength: 9 },
    { name: 'Suriname',                 iso2: 'SR', dialCode: '+597',  flag: getFlag('SR'), maxLength: 7 },
    { name: 'Sweden',                   iso2: 'SE', dialCode: '+46',   flag: getFlag('SE'), maxLength: 10 },
    { name: 'Switzerland',              iso2: 'CH', dialCode: '+41',   flag: getFlag('CH'), maxLength: 9 },
    { name: 'Syria',                    iso2: 'SY', dialCode: '+963',  flag: getFlag('SY'), maxLength: 9 },
    { name: 'Taiwan',                   iso2: 'TW', dialCode: '+886',  flag: getFlag('TW'), maxLength: 9 },
    { name: 'Tajikistan',               iso2: 'TJ', dialCode: '+992',  flag: getFlag('TJ'), maxLength: 9 },
    { name: 'Tanzania',                 iso2: 'TZ', dialCode: '+255',  flag: getFlag('TZ'), maxLength: 9 },
    { name: 'Thailand',                 iso2: 'TH', dialCode: '+66',   flag: getFlag('TH'), maxLength: 9 },
    { name: 'Togo',                     iso2: 'TG', dialCode: '+228',  flag: getFlag('TG'), maxLength: 8 },
    { name: 'Trinidad and Tobago',      iso2: 'TT', dialCode: '+1868', flag: getFlag('TT'), maxLength: 7 },
    { name: 'Tunisia',                  iso2: 'TN', dialCode: '+216',  flag: getFlag('TN'), maxLength: 8 },
    { name: 'Turkey',                   iso2: 'TR', dialCode: '+90',   flag: getFlag('TR'), maxLength: 10 },
    { name: 'Turkmenistan',             iso2: 'TM', dialCode: '+993',  flag: getFlag('TM'), maxLength: 8 },
    { name: 'Uganda',                   iso2: 'UG', dialCode: '+256',  flag: getFlag('UG'), maxLength: 9 },
    { name: 'Ukraine',                  iso2: 'UA', dialCode: '+380',  flag: getFlag('UA'), maxLength: 9 },
    { name: 'United Arab Emirates',     iso2: 'AE', dialCode: '+971',  flag: getFlag('AE'), maxLength: 9 },
    { name: 'Uruguay',                  iso2: 'UY', dialCode: '+598',  flag: getFlag('UY'), maxLength: 8 },
    { name: 'Uzbekistan',               iso2: 'UZ', dialCode: '+998',  flag: getFlag('UZ'), maxLength: 9 },
    { name: 'Venezuela',                iso2: 'VE', dialCode: '+58',   flag: getFlag('VE'), maxLength: 10 },
    { name: 'Vietnam',                  iso2: 'VN', dialCode: '+84',   flag: getFlag('VN'), maxLength: 10 },
    { name: 'Yemen',                    iso2: 'YE', dialCode: '+967',  flag: getFlag('YE'), maxLength: 9 },
    { name: 'Zambia',                   iso2: 'ZM', dialCode: '+260',  flag: getFlag('ZM'), maxLength: 9 },
    { name: 'Zimbabwe',                 iso2: 'ZW', dialCode: '+263',  flag: getFlag('ZW'), maxLength: 9 },
];


export function getCountryByISO2(iso2: string): Country | undefined {
    return COUNTRY_CODE.find(c => c.iso2.toUpperCase() === iso2.toUpperCase());
}

export function getCountryByDialCode(dialCode: string): Country | undefined {
    const normalized = dialCode.startsWith('+') ? dialCode : `+${dialCode}`;
    return COUNTRY_CODE.find(c => c.dialCode === normalized);
}